plugins:
  ldap_enabled:
    default: true
  ldap_user_create_mode:
    type: enum
    default: "auto"
    choices:
      - auto
      - list
      - none
  ldap_lookup_users_by:
    type: enum
    default: "email"
    choices:
      - email
      - username
  ldap_hostname:
    default: "adfs.example.com"
  ldap_port:
    default: 389
    min: 0
    max: 65535
  ldap_method:
    type: enum
    default: "plain"
    choices:
      - ssl
      - tls
      - plain
  ldap_base:
    default: "dc=example,dc=com"
  ldap_uid:
    default: "sAMAccountName"
  ldap_bind_dn:
    default: ""
  ldap_password:
    default: ""
    secret: true
  ldap_filter:
    default: ""
